/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackBar: typeof import('./src/components/BackBar.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopBar: typeof import('./src/components/ShopBar.vue')['default']
    ShopCard: typeof import('./src/components/ShopCard.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
